### ISSUE TITLE
Still todo before publishing

### ISSUE THREAD

**Issue by simina-cotop** [simina-cotop/simina-cotop.github.io#14]
**Hobbies and Interests**

- [x] Figure out the spacing for Movie Blog Coming Soon
- [x] All the other stuff from Issue #12 
- [x] Check if images are embedded correctly

**General**

- [ ] Figure out the space between sections on a page
- [x] Link Colors

**Work and Education**

- [x] Content for Program of Psycho-Pedagogical Training, 
- [x] Education, 
- [x] Projects
- [x] The title for Program of Psycho-Pedagogical Training
- [x] Add a tiny person emoji to the left of the supervisors

**Index page**

- [x] Add color
- [x] Double check content + maybe rewrite
- [x] Fix navbar spacing

**Non-code stuff**
- [ ] Buy domain + email address
- [ ] Finish updating the LinkedIn profile + add the correct link
- [ ] Improve GitHub profile
