### ISSUE TITLE
Still todo

### ISSUE THREAD

**Issue by simina-cotop** [simina-cotop/simina-cotop.github.io#18]
**General**
- [ ] Fix spacing between sections on the Hobbies page
- [x] Improve responsive design

**Non-code stuff**
- [x] Buy domain + email address
- [ ] Finish updating the LinkedIn profile + add the correct link
- [ ] Improve GitHub profile
